// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, type, config, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, type, config, created_by, created_at, updated_at
`

type CreateAgentParams struct {
	Name      string    `json:"name"`
	Type      AgentType `json:"type"`
	Config    []byte    `json:"config"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT 
    a.id,
    a.name,
    a.type,
    a.config,
    a.created_by,
    a.created_at,
    a.updated_at,
    u.id as creator_id,
    u.email as creator_email,
    u.username as creator_username,
    u.avatar_url as creator_avatar_url
FROM agents a
LEFT JOIN users u ON a.created_by = u.id
WHERE a.id = $1
`

type GetAgentRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Type             AgentType   `json:"type"`
	Config           []byte      `json:"config"`
	CreatedBy        uuid.UUID   `json:"created_by"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	CreatorID        pgtype.UUID `json:"creator_id"`
	CreatorEmail     pgtype.Text `json:"creator_email"`
	CreatorUsername  pgtype.Text `json:"creator_username"`
	CreatorAvatarUrl pgtype.Text `json:"creator_avatar_url"`
}

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorID,
		&i.CreatorEmail,
		&i.CreatorUsername,
		&i.CreatorAvatarUrl,
	)
	return i, err
}

const listAgentsByCreator = `-- name: ListAgentsByCreator :many
SELECT 
    a.id,
    a.name,
    a.type,
    a.config,
    a.created_by,
    a.created_at,
    a.updated_at,
    u.id as creator_id,
    u.email as creator_email,
    u.username as creator_username,
    u.avatar_url as creator_avatar_url
FROM agents a
LEFT JOIN users u ON a.created_by = u.id
WHERE a.created_by = $1
ORDER BY a.created_at DESC
`

type ListAgentsByCreatorRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Type             AgentType   `json:"type"`
	Config           []byte      `json:"config"`
	CreatedBy        uuid.UUID   `json:"created_by"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	CreatorID        pgtype.UUID `json:"creator_id"`
	CreatorEmail     pgtype.Text `json:"creator_email"`
	CreatorUsername  pgtype.Text `json:"creator_username"`
	CreatorAvatarUrl pgtype.Text `json:"creator_avatar_url"`
}

func (q *Queries) ListAgentsByCreator(ctx context.Context, createdBy uuid.UUID) ([]ListAgentsByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listAgentsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsByCreatorRow{}
	for rows.Next() {
		var i ListAgentsByCreatorRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorEmail,
			&i.CreatorUsername,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE agents
SET 
    name = COALESCE($2, name),
    type = COALESCE($3, type),
    config = COALESCE($4, config),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentParams struct {
	ID     uuid.UUID     `json:"id"`
	Name   pgtype.Text   `json:"name"`
	Type   NullAgentType `json:"type"`
	Config []byte        `json:"config"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.Exec(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	return err
}
