// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, owner_id, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	OwnerID     uuid.UUID   `json:"owner_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.Description, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT 
    p.id, 
    p.name, 
    p.description, 
    p.owner_id, 
    p.created_at, 
    p.updated_at,
    u.id as user_id,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM projects p
LEFT JOIN users u ON p.owner_id = u.id
WHERE p.id = $1
LIMIT 1
`

type GetProjectByIDRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	OwnerID       uuid.UUID   `json:"owner_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	UserID        pgtype.UUID `json:"user_id"`
	UserEmail     pgtype.Text `json:"user_email"`
	UserUsername  pgtype.Text `json:"user_username"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserUsername,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT 
    p.id, 
    p.name, 
    p.description, 
    p.owner_id, 
    p.created_at, 
    p.updated_at,
    u.id as user_id,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM projects p
LEFT JOIN users u ON p.owner_id = u.id
WHERE p.owner_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsByOwnerRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	OwnerID       uuid.UUID   `json:"owner_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	UserID        pgtype.UUID `json:"user_id"`
	UserEmail     pgtype.Text `json:"user_email"`
	UserUsername  pgtype.Text `json:"user_username"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]ListProjectsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByOwnerRow{}
	for rows.Next() {
		var i ListProjectsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.UserEmail,
			&i.UserUsername,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description)
WHERE id = $3
RETURNING id, name, description, owner_id, created_at, updated_at
`

type UpdateProjectParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.Description, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
