// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProjectRole `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const deleteProjectMember = `-- name: DeleteProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) error {
	_, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT 
    pm.project_id,
    pm.user_id,
    pm.role,
    pm.created_at,
    u.id as user_id_col,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM project_members pm
LEFT JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1 AND pm.user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetProjectMemberRow struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	UserID        uuid.UUID   `json:"user_id"`
	Role          ProjectRole `json:"role"`
	CreatedAt     time.Time   `json:"created_at"`
	UserIDCol     pgtype.UUID `json:"user_id_col"`
	UserEmail     pgtype.Text `json:"user_email"`
	UserUsername  pgtype.Text `json:"user_username"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i GetProjectMemberRow
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UserIDCol,
		&i.UserEmail,
		&i.UserUsername,
		&i.UserAvatarUrl,
	)
	return i, err
}

const getProjectMembers = `-- name: GetProjectMembers :many
SELECT 
    pm.project_id,
    pm.user_id,
    pm.role,
    pm.created_at,
    u.id as user_id_col,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM project_members pm
LEFT JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1
ORDER BY 
    CASE pm.role 
        WHEN 'admin' THEN 1 
        WHEN 'member' THEN 2 
        WHEN 'agent' THEN 3 
        WHEN 'guest' THEN 4 
    END,
    u.username
`

type GetProjectMembersRow struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	UserID        uuid.UUID   `json:"user_id"`
	Role          ProjectRole `json:"role"`
	CreatedAt     time.Time   `json:"created_at"`
	UserIDCol     pgtype.UUID `json:"user_id_col"`
	UserEmail     pgtype.Text `json:"user_email"`
	UserUsername  pgtype.Text `json:"user_username"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
}

func (q *Queries) GetProjectMembers(ctx context.Context, projectID uuid.UUID) ([]GetProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, getProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectMembersRow{}
	for rows.Next() {
		var i GetProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserIDCol,
			&i.UserEmail,
			&i.UserUsername,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProjectRole = `-- name: GetUserProjectRole :one
SELECT role FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetUserProjectRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserProjectRole(ctx context.Context, arg GetUserProjectRoleParams) (ProjectRole, error) {
	row := q.db.QueryRow(ctx, getUserProjectRole, arg.ProjectID, arg.UserID)
	var role ProjectRole
	err := row.Scan(&role)
	return role, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProjectRole `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
