// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_agents.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectAgent = `-- name: AddProjectAgent :exec
INSERT INTO project_agents (project_id, agent_id, role, config_override, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type AddProjectAgentParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	AgentID        uuid.UUID   `json:"agent_id"`
	Role           ProjectRole `json:"role"`
	ConfigOverride []byte      `json:"config_override"`
	CreatedBy      uuid.UUID   `json:"created_by"`
}

func (q *Queries) AddProjectAgent(ctx context.Context, arg AddProjectAgentParams) error {
	_, err := q.db.Exec(ctx, addProjectAgent,
		arg.ProjectID,
		arg.AgentID,
		arg.Role,
		arg.ConfigOverride,
		arg.CreatedBy,
	)
	return err
}

const deleteProjectAgent = `-- name: DeleteProjectAgent :exec
DELETE FROM project_agents
WHERE project_id = $1 AND agent_id = $2
`

type DeleteProjectAgentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	AgentID   uuid.UUID `json:"agent_id"`
}

func (q *Queries) DeleteProjectAgent(ctx context.Context, arg DeleteProjectAgentParams) error {
	_, err := q.db.Exec(ctx, deleteProjectAgent, arg.ProjectID, arg.AgentID)
	return err
}

const getProjectAgent = `-- name: GetProjectAgent :one
SELECT 
    pa.id,
    pa.project_id,
    pa.agent_id,
    pa.role,
    pa.config_override,
    pa.created_by,
    pa.created_at,
    a.id as agent_id_col,
    a.name as agent_name,
    a.type as agent_type,
    a.config as agent_config
FROM project_agents pa
LEFT JOIN agents a ON pa.agent_id = a.id
WHERE pa.project_id = $1 AND pa.agent_id = $2
`

type GetProjectAgentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	AgentID   uuid.UUID `json:"agent_id"`
}

type GetProjectAgentRow struct {
	ID             uuid.UUID     `json:"id"`
	ProjectID      uuid.UUID     `json:"project_id"`
	AgentID        uuid.UUID     `json:"agent_id"`
	Role           ProjectRole   `json:"role"`
	ConfigOverride []byte        `json:"config_override"`
	CreatedBy      uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time     `json:"created_at"`
	AgentIDCol     pgtype.UUID   `json:"agent_id_col"`
	AgentName      pgtype.Text   `json:"agent_name"`
	AgentType      NullAgentType `json:"agent_type"`
	AgentConfig    []byte        `json:"agent_config"`
}

func (q *Queries) GetProjectAgent(ctx context.Context, arg GetProjectAgentParams) (GetProjectAgentRow, error) {
	row := q.db.QueryRow(ctx, getProjectAgent, arg.ProjectID, arg.AgentID)
	var i GetProjectAgentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Role,
		&i.ConfigOverride,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AgentIDCol,
		&i.AgentName,
		&i.AgentType,
		&i.AgentConfig,
	)
	return i, err
}

const getProjectAgentByID = `-- name: GetProjectAgentByID :one
SELECT 
    pa.id,
    pa.project_id,
    pa.agent_id,
    pa.role,
    pa.config_override,
    pa.created_by,
    pa.created_at
FROM project_agents pa
WHERE pa.id = $1
`

func (q *Queries) GetProjectAgentByID(ctx context.Context, id uuid.UUID) (ProjectAgent, error) {
	row := q.db.QueryRow(ctx, getProjectAgentByID, id)
	var i ProjectAgent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Role,
		&i.ConfigOverride,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectAgents = `-- name: GetProjectAgents :many
SELECT 
    pa.id,
    pa.project_id,
    pa.agent_id,
    pa.role,
    pa.config_override,
    pa.created_by,
    pa.created_at,
    a.id as agent_id_col,
    a.name as agent_name,
    a.type as agent_type,
    a.config as agent_config
FROM project_agents pa
LEFT JOIN agents a ON pa.agent_id = a.id
WHERE pa.project_id = $1
ORDER BY 
    CASE pa.role 
        WHEN 'admin' THEN 1 
        WHEN 'member' THEN 2 
        WHEN 'agent' THEN 3 
        WHEN 'guest' THEN 4 
    END,
    a.name
`

type GetProjectAgentsRow struct {
	ID             uuid.UUID     `json:"id"`
	ProjectID      uuid.UUID     `json:"project_id"`
	AgentID        uuid.UUID     `json:"agent_id"`
	Role           ProjectRole   `json:"role"`
	ConfigOverride []byte        `json:"config_override"`
	CreatedBy      uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time     `json:"created_at"`
	AgentIDCol     pgtype.UUID   `json:"agent_id_col"`
	AgentName      pgtype.Text   `json:"agent_name"`
	AgentType      NullAgentType `json:"agent_type"`
	AgentConfig    []byte        `json:"agent_config"`
}

func (q *Queries) GetProjectAgents(ctx context.Context, projectID uuid.UUID) ([]GetProjectAgentsRow, error) {
	rows, err := q.db.Query(ctx, getProjectAgents, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectAgentsRow{}
	for rows.Next() {
		var i GetProjectAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.Role,
			&i.ConfigOverride,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AgentIDCol,
			&i.AgentName,
			&i.AgentType,
			&i.AgentConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
