// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListProjectsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Project, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
