// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, status, priority, assignee_id, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, title, description, status, priority, assignee_id, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   uuid.UUID          `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      TaskStatus         `json:"status"`
	Priority    TaskPriority       `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT 
    t.id, 
    t.project_id, 
    t.title, 
    t.description, 
    t.status, 
    t.priority, 
    t.assignee_id, 
    t.due_date,
    t.created_at, 
    t.updated_at,
    u.id as user_id,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM tasks t
LEFT JOIN users u ON t.assignee_id = u.id
WHERE t.id = $1
LIMIT 1
`

type GetTaskByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        TaskStatus         `json:"status"`
	Priority      TaskPriority       `json:"priority"`
	AssigneeID    pgtype.UUID        `json:"assignee_id"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserEmail     pgtype.Text        `json:"user_email"`
	UserUsername  pgtype.Text        `json:"user_username"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.UserEmail,
		&i.UserUsername,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT 
    t.id, 
    t.project_id, 
    t.title, 
    t.description, 
    t.status, 
    t.priority, 
    t.assignee_id, 
    t.due_date,
    t.created_at, 
    t.updated_at,
    u.id as user_id,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM tasks t
LEFT JOIN users u ON t.assignee_id = u.id
WHERE t.project_id = $1
ORDER BY t.created_at DESC
`

type ListTasksByProjectRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        TaskStatus         `json:"status"`
	Priority      TaskPriority       `json:"priority"`
	AssigneeID    pgtype.UUID        `json:"assignee_id"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserEmail     pgtype.Text        `json:"user_email"`
	UserUsername  pgtype.Text        `json:"user_username"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, projectID uuid.UUID) ([]ListTasksByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByProjectRow{}
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.UserEmail,
			&i.UserUsername,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT 
    t.id, 
    t.project_id, 
    t.title, 
    t.description, 
    t.status, 
    t.priority, 
    t.assignee_id, 
    t.due_date,
    t.created_at, 
    t.updated_at,
    u.id as user_id,
    u.email as user_email,
    u.username as user_username,
    u.avatar_url as user_avatar_url
FROM tasks t
LEFT JOIN users u ON t.assignee_id = u.id
JOIN projects p ON t.project_id = p.id
LEFT JOIN project_members pm ON p.id = pm.project_id AND pm.user_id = $1
WHERE p.owner_id = $1 OR pm.user_id = $1
ORDER BY t.created_at DESC
`

type ListTasksByUserRow struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        TaskStatus         `json:"status"`
	Priority      TaskPriority       `json:"priority"`
	AssigneeID    pgtype.UUID        `json:"assignee_id"`
	DueDate       pgtype.Timestamptz `json:"due_date"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserEmail     pgtype.Text        `json:"user_email"`
	UserUsername  pgtype.Text        `json:"user_username"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListTasksByUser(ctx context.Context, userID uuid.UUID) ([]ListTasksByUserRow, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByUserRow{}
	for rows.Next() {
		var i ListTasksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.UserEmail,
			&i.UserUsername,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    status = COALESCE($3, status),
    priority = COALESCE($4, priority),
    assignee_id = COALESCE($5, assignee_id),
    due_date = COALESCE($6, due_date)
WHERE id = $7
RETURNING id, project_id, title, description, status, priority, assignee_id, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      NullTaskStatus     `json:"status"`
	Priority    NullTaskPriority   `json:"priority"`
	AssigneeID  pgtype.UUID        `json:"assignee_id"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.DueDate,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
